# Generated by Django 4.0.1 on 2022-09-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_roommember_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='transcript',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
